# -*- coding: utf-8 -*-
"""산불 발생건수

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E7w7iBLf-h8M-6KTRyXprTn46aztXty
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("산불 발생 현황 시각화")

df = pd.read_csv("산불_월별_원인별_발생건수.csv")

selected_month = st.selectbox("월 선택", sorted(df['월'].unique()))
filtered = df[df['월'] == selected_month]

fig = px.bar(filtered, x='원인', y='발생건수', color='원인', title=f"{selected_month} 산불 원인별 발생건수")
st.plotly_chart(fig)